name: 'Dependency Scanner'
description: 'Build semantic tree'
author: 'dependency-management'
inputs:
  dependencies: 
    required: true
    description: 'iList of project dependencies'
runs:
  using: 'node16'
  main: 'dist/index.js'
